POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMTFAZXhhbXBsZS5jb20iLCJleHAiOjE3MTc1OTIxMDUsInVzZXJJZCI6MX0.00pdeq95hcDYQ2EyM0mQc6aSKPGznpfvYk6jn2Y7yik

{
    "Name": "Test-event 777722",
    "Description": "Another test event!!!22!!",
    "Location": "a test location",
    "DateTime": "2025-01-01T15:30:00Z"
}