DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMTFAZXhhbXBsZS5jb20iLCJleHAiOjE3MTY5ODU1MzIsInVzZXJJZCI6Mn0.tU_3qFUsAtV21bQNfbhtQL1fgejxip1Beb8vhsst5pc