DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2OTg0NDAyLCJ1c2VySWQiOjF9.V_aNNYFxZFoNL7gqg24pkxN5nXOTOPmpYTHYl9du6S0