POST http://localhost:8080/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMTFAZXhhbXBsZS5jb20iLCJleHAiOjE3MTc1OTIxMDUsInVzZXJJZCI6MX0.00pdeq95hcDYQ2EyM0mQc6aSKPGznpfvYk6jn2Y7yik

{
    "email": "test2@example.com",
    "password": "test!!!!!"
}